package com.aiton.bamin.driver.modle;

/**
 * Created by zjb on 2016/4/14.
 */
public class Voice {

    /**
     * errNum : 0
     * retMsg : success
     * retData : //MoxAAJSImAIU8wAWaY0PUbUSgQgcC5E0LAkxbxxqtSGgoGe+4CsQxWRJQAEOTJp8RVCH67JY4ofYsIPmgEQIAyMM35QCQO//MoxBUR0N6EIZugAugaQkPh8gvxYwMorDZANQ88DSkwsfImRcBSEGWwLAxZn3+T7LP////////pLtf//rmaFQA7aALQB/EH//MoxAgPCObQf814AAWolTVtSwUAlSKGphjD1NbW+KQC+qxanrZ4bgKhxV7O8o8iZ3T/ETTsMf////lOmhFv+XQqAghB/FhO//MoxAYNiQrBkASQNEjybLXOgPEQBMDQ2VWAlw6U8/FkAJiK3+MB8PUFjm6cVNae0AHDhT9KDtBQzD3ZzlURVuu2yW36KE0F//MoxAoOiSL2WFPOhmDIiTNRMUf9Q70cCRPfHgChIvxGAObbOGzfHiRFLVFIDiQ62o6QdIBPrIJR12SqtCr1QYhkASHrajIC//MoxAoMmYbAAFAHDJCGXzTf6t8Jk9CI67u7hBui/DufB8LDefCJ9LTiau64DzmJzgnZicP1Ats111iSadHErSo06sPD1iIe//MoxBIPWALyXgiEvoeS3LCQPH1Y0UTqrp9Z1pg8hn1sPZODbh4UOunywABcTs0fuvQtxLrh7tMqA2/3/+rSqBKZo7FWHdCI//MoxA8PsHb2XAAGAo1pEIJZ8weE58gEQiREgfOiay4eAHZqhxtBELkzk0Xa0MS5xn25X1CBqNbNmlH+MgB7mpeYjAFV6ePi//MoxAsO8JLbGAbwJDDzKMY/qGNNQYJAWhMTfWk058nHEDjIJisnnLcbpK+Fd0GuUVOFhaCY75z/+28d66IHxT//e+/BD4Nc//MoxAoPmZKxgVpoAF1lW8IVYsXo4Y5r68NtfJBAUIwFLKTnyIEnMjSr1pjiN0P6l/9NX+yRd/W1ZIov/mT/Dv31CV40ggQE//MoxAYMkHapn5JoAgGBRoAADpc1wDaEopk0uGtA2MrNgO0AXQutL5kf8qGmer/n6/6v/9U7/7v6lcwNEiK8TuARCzn0Ay0F//MoxA4QiW60AZGAAMJx3kUNA+ILPiz/JxabClwsoHGPH9DNjU6Xy5/W5vnkykUlGf9l/PlU+aX//OHP/6P///WqMgAfrP/+//MoxAYM6NrdkclIALQDW/6oYaVZylHahQ5B0G2VhUWChcspNVeWSjTr3yjbffXeAGkRcgOJAg+bOU0iOAEIgDGOE6P86Fs3//MoxA0NALrNlANSCMpgICOf2RgkizphcmDOS6MjQGv4QXafDy1g4HVX5bLKS4wpqmf/6QYoEhAHxVFoutysNR58d4amn5Bh//MoxBQMEVrFjGrErOG3vD+JDtXKhRdeK+CN6G830/N5itzCTEh//orVAGSw+1IUAD/+QhAmuuzMKmZfnQBF3byoZduFAWSW//MoxB4M4ILOP0kQAFnYK7jsRFYKnal/U9Q8Z//xh4SqeSX/iECU0Q/kvUzUDOws/bE6gdBJHgnZDJcSQSg1bj6UigSaTHk///MoxCUWUaKkAZhoAJ8oMXy4ipMzW/y8yBIGp9BZJj2SNv7miCRqmmtvX/y4sFiT3JV/vcQFrn//rLOHGzbT9HqVCADxgDA///MoxAYNONK9lc9YAPa1uxt5KgCtliwnz7adVxxAO6zX/5daAKE1tf8Es3X//a41PMgqdLf///////80QPAwPMGc6zM5QB8q//MoxAwMoM6ozA4aMH/fMeSsKEKOBwrbeSYcsOITFvrIgSERp0eszPnjI1X///////9xuggcXwGAfyYGqC4ist+QwcgBgxcN//MoxBQM2RK8/JiTCL81J77QMBEm/UpH9RYAc0SZP6Ch5dtb5zg///+zr8Q1HgyQf//FTeAWTy19thyGQgzpli40gGscBqZ///MoxBsMOVrAWHhG0f//d29WZmeniRQz8RHDgbINQXRj//r1EqDaYDWlwwPlAnAQQDdpcOIkAI0baKKlk2T5r6bt/85ZIEIY//MoxCUMKVKwAJAHKMICAw0YYOJ2le//bRkSlLds3ZlBkz//BNn+kCIM/jAACFaSaNGsh+mRrRZo6ohPKpFqCJbpBzn3/Mr///MoxC8MaQcKWAJGHuMoQgiAGh5QXaptnyCtVUG3PY+oskaCCNMts4CuB5+FAniw/KjVuRt5f0+n2807RCTK7am15eoBY4Uh//MoxDgM0Va9iAPUGFvj0AD4JwfcTfO8X0d55Q4y0VjsCctsNJS8Oee1EwlfLh6tm+X0fPbqtOzdv/t31QiAKTAHoDXWau8E//MoxD8M+LrS9gPaEGW7V5sjdj5xkGcecbF6jg2tQJvCXw8/VvT5vt/yutlDrpLZu9P+9Qr0JnWgkyNwdHjz1klCLuQLGbiM//MoxEYMYVK1jAPKGMPBurFYjBAARH7yUTru2sv+DZ8Fn+erJ6IiAiw0yhARIQlVbkh3MlhDRBKU21iIfG8ASCHIpDVtsLFH//MoxE8MuKKY0A5WFC5f39U1mwcUJgwWV//6Wh17///9TRM5NQDVJbQBv+AB9ZdASpHGDBXhFsSRLDtOMs4bJGyel0dm/6dU//MoxFcM2HKEKg7wBHXoYvT/y/m/9W6gQCdiyoAW7La5p9wIOIyZClASJXrMY7DScFazpXv+eUVc3/t8S/Bp8kor/kv+dZ////MoxF4MagLOXmgFK/CdzSJ2IsM1lymIpFFnQSwLVHcCthWYUMWzQ0UvYI19wAUEaB6NLa///+sUbiwrTEFNRTMuOTkuNVVV//MoxGcMMDKJvgheAlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy45OS41VVVVVVVVVVVV//MoxHEKeF2gCMJCoFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy45OS41VVVVVVVVVVVV//MoxIIAAANIAAAAAFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy45OS41VVVVVVVVVVVV//MoxL0AAANIAAAAAFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//MoxMQAAANIAAAAAFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//MoxMQAAANIAAAAAFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//MoxMQAAANIAAAAAFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
     */

    private int errNum;
    private String retMsg;
    private String retData;

    public int getErrNum() {
        return errNum;
    }

    public void setErrNum(int errNum) {
        this.errNum = errNum;
    }

    public String getRetMsg() {
        return retMsg;
    }

    public void setRetMsg(String retMsg) {
        this.retMsg = retMsg;
    }

    public String getRetData() {
        return retData;
    }

    public void setRetData(String retData) {
        this.retData = retData;
    }
}
